FROM python:3.11

RUN mkdir /app
RUN mkdir -p /data
COPY . /app
WORKDIR /app
RUN python -m pip install -r requirements.txt
ENV FLASK_APP=node_server.py

# Ensure the data directory exists and is writable
RUN chmod 777 /data

ENTRYPOINT [ "flask", "run", "--host", "0.0.0.0" ]